# Generated by Django 5.2.8 on 2025-11-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(help_text='URL de la imagen del juego')),
                ('link_url', models.URLField(help_text='Enlace al juego o tienda')),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
