# Generated by Django 4.2.24 on 2025-11-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="discount",
            field=models.IntegerField(
                default=0, help_text="Porcentaje de descuento (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
