# Generated by Django 5.2.7 on 2025-11-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tweet_is_retweet_tweet_parent_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Temas",
            },
        ),
        migrations.AddField(
            model_name="tweet",
            name="temas",
            field=models.ManyToManyField(
                blank=True, related_name="tweets", to="core.tema"
            ),
        ),
    ]
