# Generated by Django 5.2.8 on 2025-11-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steam_id',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
