# Generated by Django 5.2.8 on 2025-11-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_level_profile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trophies',
            field=models.IntegerField(default=0),
        ),
    ]
