# Generated by Django 5.2.8 on 2025-11-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games_cache',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
