# Generated by Django 5.2.8 on 2025-11-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_games_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(default='NOVATO', max_length=50),
        ),
    ]
